/*

schema for allwise table.

Model can be found at http://wise2.ipac.caltech.edu/docs/release/allwise/expsup/sec2_1a.html


*/

CREATE TABLE catalogdb.allwise(
    designation varchar(20),
    ra double precision,
    dec double precision,
    sigra double precision,
    sigdec double precision,
    sigradec double precision,
    glon double precision,
    glat double precision,
    elon double precision,
    elat double precision,
    wx double precision,
    wy double precision,
    cntr bigint,
    source_id varchar(28),
    coadd_id varchar(20),
    src integer,
    w1mpro real,
    w1sigmpro real,
    w1snr real,
    w1rchi2 real,
    w2mpro real,
    w2sigmpro real,
    w2snr real,
    w2rchi2 real,
    w3mpro real,
    w3sigmpro real,
    w3snr real,
    w3rchi2 real,
    w4mpro real,
    w4sigmpro real,
    w4snr real,
    w4rchi2 real,
    rchi2 real,
    nb integer,
    na integer,
    w1sat real,
    w2sat real,
    w3sat real,
    w4sat real,
    satnum char(4),
    ra_pm double precision,
    dec_pm double precision,
    sigra_pm real,
    sigdec_pm real,
    sigradec_pm real,
    pmra integer,
    sigpmra integer,
    pmdec integer,
    sigpmdec integer,
    w1rchi2_pm real,
    w2rchi2_pm real,
    w3rchi2_pm real,
    w4rchi2_pm real,
    rchi2_pm real,
    pmcode char(5),
    cc_flags char(4),
    rel char(1),
    ext_flg integer,
    var_flg char(4),
    ph_qual char(4),
    det_bit integer,
    moon_lev char(4),
    w1nm integer,
    w1m integer,
    w2nm integer,
    w2m integer,
    w3nm integer,
    w3m integer,
    w4nm integer,
    w4m integer,
    w1cov real,
    w2cov real,
    w3cov real,
    w4cov real,
    w1cc_map integer,
    w1cc_map_str varchar(9),
    w2cc_map integer,
    w2cc_map_str varchar(9),
    w3cc_map integer,
    w3cc_map_str varchar(9),
    w4cc_map integer,
    w4cc_map_str varchar(9),
    use_src integer,
    best_use_cntr bigint,
    ngrp integer,
    w1flux double precision,
    w1sigflux double precision,
    w1sky real,
    w1sigsk real,
    w1conf real,
    w2flux double precision,
    w2sigflux double precision,
    w2sky real,
    w2sigsk real,
    w2conf real,
    w3flux double precision,
    w3sigflux double precision,
    w3sky real,
    w3sigsk real,
    w3conf real,
    w4flux double precision,
    w4sigflux double precision,
    w4sky real,
    w4sigsk real,
    w4conf real,
    w1mag double precision,
    w1sigm double precision,
    w1flg integer,
    w1mcor real,
    w2mag double precision,
    w2sigm double precision,
    w2flg integer,
    w2mcor real,
    w3mag double precision,
    w3sigm double precision,
    w3flg integer,
    w3mcor real,
    w4mag double precision,
    w4sigm double precision,
    w4flg integer,
    w4mcor real,
    w1mag_1 double precision,
    w1sigm_1 double precision,
    w1flg_1 integer,
    w2mag_1 double precision,
    w2sigm_1 double precision,
    w2flg_1 integer,
    w3mag_1 double precision,
    w3sigm_1 double precision,
    w3flg_1 integer,
    w4mag_1 double precision,
    w4sigm_1 double precision,
    w4flg_1 integer,
    w1mag_2 double precision,
    w1sigm_2 double precision,
    w1flg_2 integer,
    w2mag_2 double precision,
    w2sigm_2 double precision,
    w2flg_2 integer,
    w3mag_2 double precision,
    w3sigm_2 double precision,
    w3flg_2 integer,
    w4mag_2 double precision,
    w4sigm_2 double precision,
    w4flg_2 integer,
    w1mag_3 double precision,
    w1sigm_3 double precision,
    w1flg_3 integer,
    w2mag_3 double precision,
    w2sigm_3 double precision,
    w2flg_3 integer,
    w3mag_3 double precision,
    w3sigm_3 double precision,
    w3flg_3 integer,
    w4mag_3 double precision,
    w4sigm_3 double precision,
    w4flg_3 integer,
    w1mag_4 double precision,
    w1sigm_4 double precision,
    w1flg_4 integer,
    w2mag_4 double precision,
    w2sigm_4 double precision,
    w2flg_4 integer,
    w3mag_4 double precision,
    w3sigm_4 double precision,
    w3flg_4 integer,
    w4mag_4 double precision,
    w4sigm_4 double precision,
    w4flg_4 integer,
    w1mag_5 double precision,
    w1sigm_5 double precision,
    w1flg_5 integer,
    w2mag_5 double precision,
    w2sigm_5 double precision,
    w2flg_5 integer,
    w3mag_5 double precision,
    w3sigm_5 double precision,
    w3flg_5 integer,
    w4mag_5 double precision,
    w4sigm_5 double precision,
    w4flg_5 integer
    w1mag_6 double precision,
    w1sigm_6 double precision,
    w1flg_6 integer,
    w2mag_6 double precision,
    w2sigm_6 double precision,
    w2flg_6 integer,
    w3mag_6 double precision,
    w3sigm_6 double precision,
    w3flg_6 integer,
    w4mag_6 double precision,
    w4sigm_6 double precision,
    w4flg_6 integer,
    w1mag_7 double precision,
    w1sigm_7 double precision,
    w1flg_7 integer,
    w2mag_7 double precision,
    w2sigm_7 double precision,
    w2flg_7 integer,
    w3mag_7 double precision,
    w3sigm_7 double precision,
    w3flg_7 integer,
    w4mag_7 double precision,
    w4sigm_7 double precision,
    w4flg_7 integer,
    w1mag_8 double precision,
    w1sigm_8 double precision,
    w1flg_8 integer,
    w2mag_8 double precision,
    w2sigm_8 double precision,
    w2flg_8 integer,
    w3mag_8 double precision,
    w3sigm_8 double precision,
    w3flg_8 integer,
    w4mag_8 double precision,
    w4sigm_8 double precision,
    w4flg_8 integer,
    w1magp double precision,
    w1sigp1 double precision,
    w1sigp2 double precision,
    w1k real,
    w1ndf integer,
    w1mlq real,
    w1mjdmin double precision,
    w1mjdmax double precision,
    w1mjdmean double precision,
    w2magp double precision,
    w2sigp1 double precision,
    w2sigp2 double precision,
    w2k real,
    w2ndf integer,
    w2mlq real,
    w2mjdmin double precision,
    w2mjdmax double precision,
    w2mjdmean double precision,
    w3magp double precision,
    w3sigp1 double precision,
    w3sigp2 double precision,
    w3k real,
    w3ndf integer,
    w3mlq real,
    w3mjdmin double precision,
    w3mjdmax double precision,
    w3mjdmean double precision,
    w4magp double precision,
    w4sigp1 double precision,
    w4sigp2 double precision,
    w4k real,
    w4ndf integer,
    w4mlq real,
    w4mjdmin double precision,
    w4mjdmax double precision,
    w4mjdmean double precision,
    rho12 integer,
    rho23 integer,
    rho34 integer,
    q12 integer,
    q23 integer,
    q34 integer,
    xscprox double precision,
    w1rsemi double precision,
    w1ba double precision,
    w1pa  double precision,
    w1gmag double precision,
    w1gerr double precision,
    w1gflg integer,
    w2rsemi double precision,
    w2ba double precision,
    w2pa double precision,
    w2gmag double precision,
    w2gerr double precision,
    w2gflg integer,
    w3rsemi double precision,
    w3ba double precision,
    w3pa double precision,
    w3gmag double precision,
    w3gerr double precision,
    w3gflg integer,
    w4rsemi double precision,
    w4ba double precision,
    w4pa double precision,
    w4gmag double precision,
    w4gerr double precision,
    w4gflg integer,
    tmass_key char(10),
    r_2mass double precision,
    pa_2mass double precision,
    n_2mass integer,
    j_m_2mass double precision,
    j_msig_2mass double precision,
    h_m_2mass double precision,
    h_msig_2mass double precision,
    k_m_2mass double precision,
    k_msig_2mass double precision,
    x double precision,
    y double precision,
    z double precision,
    spt_ind bigint,
    htm20 bigint
);





