/*

schema for tess:

https://archive.stsci.edu/missions/tess/catalogs/tic_v6/tic_column_description.txt

*/

CREATE TABLE catalogdb.tess_input_v6 (
    ID bigint,
    version varchar(8),
    HIP integer,
    TYC varchar(12),
    UCAC varchar(10),
    TWOMASS varchar(20),
    SDSS bigint,
    ALLWISE varchar(20),
    GAIA varchar(20),
    APASS varchar(30),
    KIC integer,
    objType varchar(10),
    typeSrc varchar(10),
    ra double precision,
    dec double precision,
    POSflag varchar(12),
    pmRA real,
    e_pmRA real,
    pmDEC real,
    e_pmDEC real,
    PMflag varchar(12),
    plx real,
    e_plx real,
    PARflag varchar(12),
    gallong double precision,
    gallat double precision,
    eclong double precision,
    eclat double precision,
    Bmag real,
    e_Bmag real,
    Vmag real,
    e_Vmag real,
    umag real,
    e_umag real,
    gmag real,
    e_gmag real,
    rmag real,
    e_rmag real,
    imag real,
    e_imag real,
    zmag real,
    e_zmag real,
    Jmag real,
    e_Jmag real,
    Hmag real,
    e_Hmag real,
    Kmag real,
    e_Kmag real,
    TWOMflag varchar(20),
    prox real,
    w1mag real,
    e_w1mag real,
    w2mag real,
    e_w2mag real,
    w3mag real,
    e_w3mag real,
    w4mag real,
    e_w4mag real,
    GAIAmag real,
    e_GAIAmag real,
    Tmag real,
    e_Tmag real,
    TESSflag varchar(20),
    SPFlag varchar(20),
    Teff real,
    e_Teff real,
    logg real,
    e_logg real,
    MH real,
    e_MH real,
    rad real,
    e_rad real,
    mass real,
    e_mass real,
    rho real,
    e_rho real,
    lumclass varchar(10),
    lum real,
    e_lum real,
    d real,
    e_d real,
    ebv real,
    e_ebv real,
    numcont integer,
    contratio real,
    disposition varchar(10),
    duplicate_i bigint,
    priority real,
    objID bigint
);
