#! /usr/bin/bash
# encoding: utf-8

# run with source (pgpass works in that case)
for file in /scratch/general/lustre/u0449727/2MASS_psc/*; do
    echo "on file $file"
    psql -h db.sdss.utah.edu -U sdssdb_admin -p 5432 sdss5db -c "COPY catalogdb.twomass_psc FROM '$file' WITH DELIMITER '|' NULL '\N' CSV;"
done

#SCN in one file
echo "start scn"
psql -h db.sdss.utah.edu -U sdssdb_admin -p 5432 sdss5db -c "COPY catalogdb.twomass_scn FROM '/scratch/general/lustre/u0449727/2MASS_scn/scn_aaa' WITH DELIMITER '|' NULL '\N' CSV;"

echo "start xsc"
#XSC is two files
psql -h db.sdss.utah.edu -U sdssdb_admin -p 5432 sdss5db -c "COPY catalogdb.twomass_xsc FROM '/scratch/general/lustre/u0449727/2MASS_xsc/xsc_aaa' WITH DELIMITER '|' NULL '\N' CSV;"
psql -h db.sdss.utah.edu -U sdssdb_admin -p 5432 sdss5db -c "COPY catalogdb.twomass_xsc FROM '/scratch/general/lustre/u0449727/2MASS_xsc/xsc_baa' WITH DELIMITER '|' NULL '\N' CSV;"
echo "done"

